### ISSUE TITLE
Numerous unexpected quotation marks in the office name

### ISSUE THREAD

**Issue by Julio974-TheHexahedron** [MEDSL/2018-elections-official#2]
I found that there were numerous quotation marks in the office name column (some other columns too, but mainly this one), for example, `PROVISIO"NA"L` on line 7259.
As I am using a python script by using
```python
exec('ls = ['+line+']')
```
, this crashes my program. I have been able to use a method to remove these marks, but it is a problem, and you might want to correct these.

**Comment by cstewartiii** [comment]
Thanks for bringing this to our attention.  It looks like someone did a global replace of NA with "NA".

**Comment by cstewartiii** [comment]
@Julio974-TheHexahedron .  Which data file were you using?

**Comment by Julio974-TheHexahedron** [comment]
I used the `precinct_2018`, sorry for forgetting to add that

**Comment by cstewartiii** [comment]
Thanks.

It looks like the problem is that in Alabama, the Provisional Ballot precinct is indicated with PROVISIONAL" (that is, the word "PROVISIONAL" followed by a double-quote).  We will change that and report.

I noticed that in Stata, and I suspect R, this doesn't cause problems because the comma that immediately follows is treated as a delimiter.  In fact, you have to trick Stata (and I suspect R) into even finding the error.  Thanks for finding this in Python.

@agadjanian @connormphillips Let me know when this is fixed.

**Comment by cstewartiii** [comment]
We've examined this problem some more, and it doesn't appear to be the data file at all.  We've viewed the data file using EMACS, which loads the file as-is, and we can't find any occurrence of PROVISIO"NA"L in the entire datafile.

You included a line of Python code in your original post.  Could you send along the complete code, so that we can figure out what's going on?

**Comment by Julio974-TheHexahedron** [comment]
Here is the (annotated) code I am using:
```python
import math

with open('precinct_2018.csv') as original:
    with open('precinct_2018.tsv') as new:
        i = 0
        parties = []
        for line in original:
            i += 1

            # Know where the program is at
            if math.log2(i).is_integer(): print(i)

            # Don't crash
            line = line.replace('FALSE','False')
            line = line.replace('TRUE','True')
            line = line.replace('NA','"NA"')
            # List formatting
            #
            #   Note: this is the line that fixes the wrong quotation marks
            #
            line = '"'+line.partition('","')[0].replace('"','')+line.partition('","')[1]+line.partition('","')[2]
            # Go to list
            exec('ls = ['+line+']')

            # Just show which parties are in the data
            party = ls[2].title()
            if party not in parties:
                parties.append(party)
                print(party)
```
(last paragraph is just something to test it, I was curious to know which parties were in the data)
When I comment out the "list formatting" line, I get a syntax error, as the line looks like this:
`'"PROVISIO"NA"L","Straight Party","democratic","election day",13,"Autauga","Autauga","Alabama Democratic Party","","all",2018,"gen","Alabama",False,False,"AL",1,63,41\n'` (the "go to list" line breaks down), `i` is 7259 at this stage.

**Comment by cstewartiii** [comment]
Thanks. -cs

-------------------------------------------------------------------------------------------------------------
Charles Stewart III
Kenan Sahin Distinguished Professor of Political Science
The Massachusetts Institute of Technology
E53-447
Cambridge, Massachusetts   02139
617-253-3127
cstewart@mit.edu

**Comment by jw2249a** [comment]
@Julio974-TheHexahedron 

This issue is caused by the fact that you're doing a replacement on a string object and not a list itself. A list will not have the replace option because it is not a string, so I wrote one up as a function. 

Further, I added the csv package so that you are iterating through a list separated by commas instead of your command as it would likely not catch NA values if the data was formatted in a program that didn't save the data as ,"NA", but instead ,NA, which does happen.

I also thing getting more familiar with reading in CSVs/TSVs from [pythons website](https://docs.python.org/3/library/csv.html) would be a better place for future questions on this. 

    import csv	
    import math

    # quick function to replace values
    def replace_value(obj, initval, replaceval):
        x = 0
        while x < len(obj):
            if obj[x] == initval:
            obj[x] = replaceval
            x+=1
        return(obj)

    with open('precinct_2018.csv') as csvfile:
        with open('precinct_2018.tsv') as new:
            original = csv.reader(csvfile, delimiter=',')
            i = 0
            parties = []
            for line in original:
                i += 1

                # Know where the program is at
                if math.log2(i).is_integer(): print(i)
   
                # Don't crash
                line = replace_value(line, 'FALSE',False)
                line = replace_value(line, 'TRUE',True)
                line = replace_value(line, 'NA', float('NaN'))
                # List formatting
                #
                #   Note: this is the line that fixes the wrong quotation marks
                #

                # Just show which parties are in the data
                party = ls[2].title()
                if party not in parties:
                    parties.append(party)
                    print(party)
